# defined using the cerberus validation API
# https://docs.python-cerberus.org/en/stable/index.html

method:
  type: dict
  schema:
    name:
      type: string
    space:
      type: string
      allowed: [l2, cosinesimil]
