# defined using the cerberus validation API
# https://docs.python-cerberus.org/en/stable/index.html

method:
  type: dict
  schema:
    name:
      type: string
    space_type:
      type: string
      allowed: [l2, cosinesimil]
    parameters:
      type: dict
      schema:
        ef_construction:
          type: integer
          min: 100
          max: 2000
        m:
          type: integer
          min: 5
          max: 100
ef_search:
  type: integer
  min: 100
  max: 2000
index_thread_qty:
  type: integer
  min: 1
  max: 10
post:
  type: integer
  min: 0
  max: 2
  default: 0
k:
  type: integer
  min: 1
  max: 10000
