# defined using the cerberus validation API
# https://docs.python-cerberus.org/en/stable/index.html

method:
  type: dict
  schema:
    name:
      type: string
    space_type:
      type: string
      allowed: [l2, cosinesimil]
    parameters:
      type: dict
      schema:
        ef_construction:
          type: integer
        ef_search:
          type: integer
        m:
          type: integer
        index_thread_qty:
          type: integer
        post:
          type: integer
