test_name: opensearch_query_test
test_id: "Example ingestion workload test"
num_runs: 15
show_runs: false
setup:
  - name: delete_index
    index_name: test_index
steps:
  - name: create_index
    index_name: test_index
    index_spec: config/opensearch/sample_index_test/index-spec.json
  - name: bulk_index
    index_name: test_index
    field_name: test_vector_2
    bulk_size: 20
    dataset_format: hdf5
    dataset_path: dataset/data.hdf5
  - name: refresh_index
    index_name: test_index
cleanup:
  - name: delete_index
    index_name: test_index